import Head from "next/head";
import Params from "../../interfaces/Params";
import { Product } from "../../interfaces/Product";
import { getProductPaths, getProductBySlug } from "../../utils/products";
import { GetStaticPaths, GetStaticProps } from "next";
import ProductPageTemplate from "../../components/templates/ProductPageTemplate";

type Props = { product: Product };

const ProductPage: React.FC<Props> = (props: Props) => {
  return (
    <div>
      <Head>
        <title>{`${props.product.name} | Audiophile`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductPageTemplate product={props.product} />
    </div>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  const paths = getProductPaths().map((path) => ({
    params: { category: path.category, slug: path.slug },
  }));

  return { paths, fallback: false };
};

export const getStaticProps: GetStaticProps = async (context) => {
  const params = context.params as Params;
  const product: Product | undefined = getProductBySlug(params.slug);

  return { props: { product } };
};

export default ProductPage;
