import Head from "next/head";
import { useRouter } from "next/router";
import { GetStaticPaths, GetStaticProps } from "next";
import { getProductsByCategory, getCategories } from "../../utils/products";
import { Product } from "../../interfaces/Product";
import CategoryTemplate from "../../components/templates/CategoryTemplate";
import Params from "../../interfaces/Params";

type Props = { products: Product[] };

const CategoryPage = (props: Props) => {
  const {
    query: { category },
  } = useRouter();
  return (
    <div>
      <Head>
        <title>{`Audiophile Product Category`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CategoryTemplate products={props.products} />
    </div>
  );
};

export default CategoryPage;

export const getStaticPaths: GetStaticPaths = async () => {
  const categories: string[] = getCategories();
  const paths = categories.map((category) => ({ params: { category } }));

  return { paths, fallback: false };
};

export const getStaticProps: GetStaticProps = async (context) => {
  const params = context.params as Params;
  const products: Product[] = getProductsByCategory(params.category);

  return { props: { products } };
};
